### PR TITLE
convert to CMake

### PR DESCRIPTION
**Pull request by DavidZemon**
That was easy.

I'm not sure how to test it. I ran it once with no arguments and it threw an error (as expected, I'm sure).

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```

Do you have a test file I can throw through the program to ensure it's working as expected?

### CODE REVIEW

**Comment by electrodude** [comment]
Feed it a Spin file as its first argument.  I think any should work; if not, tell me and I'll give you one that does.

**Comment by DavidZemon** [comment]
Glad I tested. Fixed the module path in main.cpp and now all is golden! It spits out a line for each section of Spin and then the source code (or something kinda like it. I didn't look too close)

**Comment by electrodude** [comment]
Thanks!  

My old Makefile automatically made everything in modules/*, without having to be told about new module subdirectories.  Is there a way to do this with CMake?  (Should I even do it?)

I'll merge this tomorrow, after I clean up my working tree to something that's not a complete mess and then test your work.

**Comment by DavidZemon** [comment]
At the moment, your modules are included via hard-coded string literals in `main.cpp`. With that in mind, I would leave them where CMake puts them by default.

I'm sure (i hope) the hard-coded string literal is a temporary measure, since you're still in the early development stage. Once the final import method is determined, then you can choose where the modules end up.

The way it's currently coded, import pattern doesn't get any more complex with the default CMake way compared to your Make method. The pattern is `./modules/<module>/lib<module>.so` instead of `./modules/<module>.so`. It's one extra instance of the variable `<module>` and three extra characters - but no added complexity. If it became more complex, I'd say fix it to be like the old way.

**Comment by electrodude** [comment]
Only libspinc.so, the core Spin compiler, will normally be loaded at startup.  libspinc.so will load the rest as requested by the input files.  When I add a proper configuration file system, there will probably be a list of what gets loaded at startup, but until then, it will remain hardcoded.  

I originally had modules get copied to the `./modules/` directory because I was planning that in a release setup the modules directory would immediately contain the module `.so` files without another layer of directories in between.  However, it's probably a good idea to give each module its own subdirectory, in case they have other dependencies.  

Also, I've decided that modules shouldn't all be automatically built - what if some are part of their own project?

**Comment by DavidZemon** [comment]
Great!

You don't need a separate project for each module. `make` or `make all` will build all targets of course, but you can also specify specific targets - each library and executable has its own Make target. So, if you specify `make esc`, it CMake will have configured the Makefiles such that only the modules set as dependencies and esc itself will be built. Exactly what you're looking for I think :)

**Comment by electrodude** [comment]
OK, thanks.  What I was trying to say was that I'm pretty sure `libspinc.so` is the only module that will ship with esc, and that any others are probably part of a separate project, i.e. are in a separate git repository, meaning that when I run `make` or `make all` no modules besides `libspinc.so` should be built, even if there are others.

**Comment by DavidZemon** [comment]
oh I see, that makes sense. I'd recommend using an install target to put all modules in normal installation directories. CMake [handles this nicely](http://www.cmake.org/cmake/help/v3.0/command/install.html). I haven't done it myself yet, but I can certainly help out when you get to that point if you need.

**Pull request merged**
